### ISSUE TITLE
Views and Twitter Blue verification appears on the right tweet sidebar when viewing media

### ISSUE THREAD

**Issue by mcpower** [insin/tweak-new-twitter#206]
Reproduced on version 2.22.1 on both Chrome Desktop and Firefox with "hide views / analytics under tweets". I assume this hasn't been fixed at HEAD.

![image](https://user-images.githubusercontent.com/6015058/214274614-70d136bd-7f86-4c5e-9a58-e45b4ae027a5.png)

**Comment by mcpower** [comment]
"Twitter Blue verified checkmarks" also do not appear on the right tweet sidebar:

![image](https://user-images.githubusercontent.com/6015058/214275500-523aab92-b4bd-40a7-826d-a82663bbdfcd.png)

**Comment by insin** [comment]
The view is an easy CSS fix, the other one not so much - the desktop media modals contain their own timeline which we're not handling, and when you switch to them the <title> doesn't change, so we need to:

- Watch for a popup appearing and the URL changing to a photo URL
- Start watching the media modal timeline (most of the current timeline watching stuff should work, probably need to be able to pass a different selector in), which will handle replacing the Twitter Blue checks
- Bonus fun - if there's media in a reply the modal switches over to that, at which point the timeline gets replaced, so we need to watch the timeline container for the timeline being replaced
- While the modal is open, hovering over stuff or anything which pops up a menu will continue to trigger popup detection, so we need to avoid having the media popup functionality above running in duplicate
- Since the same media modal element stays the whole time, we should be able to use the existing functionality for doing something when a popup closes
