### ISSUE TITLE
Request: option to disable keyboard shortcuts

### ISSUE THREAD

**Issue by ivalith** [insin/tweak-new-twitter#213]
An issue I tend to have semi-frequently is that keyboard shortcuts capture my input when I don't intend them to after events such as the "your tweet was sent" notification at the bottom of the screen and I was wondering if it was possible to have an option to disable keyboard shortcuts entirely. Often when this happens I'll intend to be typing and open a menu or begin a search I never meant to and it's become a source of frustration with twitter.

**Comment by insin** [comment]
I'm not sure if this is possible due to how React implements event handling. If the keyboard shortcuts are implemented as global event handlers then there's not really much we can do about it from the outside (and some of the things we could try might break the app in unexpected ways)

I've tried disabling the event handlers on some of the layers of elements wrapping the app, but it doesn't seem to do anything to the keyboard shortcuts. Theoretically if keyboard shortcuts are handles in one of those layers we should be able to add an event listener lower down and stop it propagating, but from that quick poke around, that doesn't seem to be the case.

**Comment by ivalith** [comment]
> I'm not sure if this is possible due to how React implements event handling. If the keyboard shortcuts are implemented as global event handlers then there's not really much we can do about it from the outside (and some of the things we could try might break the app in unexpected ways)
> 
> I've tried disabling keyboard event handlers on some of the layers of elements wrapping the app using browser development tools, but it didn't seem to affect keyboard shortcuts. Theoretically if keyboard shortcuts are handled in one of those layers we should be able to add an event listener lower down and stop it propagating, but from a quick poke around, that doesn't seem to be the case.

Thank you for looking into it even if it doesn't end up being possible

**Comment by insin** [comment]
This would make it, uh, extremely non-trivial to do this, so I'm going to have to say no for now:

https://twitter.com/monasticpanic/status/1618964909999673344
