### ISSUE TITLE
Hide "More Tweets" does not work

### ISSUE THREAD

**Issue by LeptoFlare** [insin/tweak-new-twitter#32]
![image](https://user-images.githubusercontent.com/47790183/99440686-e97efc00-28e4-11eb-936c-3fd6b7846c45.png)

![image](https://user-images.githubusercontent.com/47790183/99440710-f0a60a00-28e4-11eb-9850-20f21f3ed08e.png)

**Comment by insin** [comment]
Could you share some of the URLs you're seeing this on?

The next version will add additional query parameters to the list it checks for to immediately click on the first tweet, which shows the full conversation instead of cutting it off "More Tweet"s, as Twitter uses different parameters to trigger it for external links (`ref_src`) vs. internal links (`s`).

**Comment by LeptoFlare** [comment]
From what I've observed, "More Tweets" will be seen in any URL that Twitter classifies as an internal link (`?s=20`)

**Comment by insin** [comment]
This should be fixed in v1.28
