### ISSUE TITLE
When Tweak New Twitter is enabled playing video keeps stopping on Twitter on Chrome MacOS

### ISSUE THREAD

**Issue by levelsio** [insin/tweak-new-twitter#33]
When Tweak New Twitter is enabled playing video keeps stopping on Twitter on Chrome MacOS

**Comment by Phidica** [comment]
@insin is there any sort of workaround for this? Perhaps that only a certain one of the settings causes this to happen and I could just turn it off? Because I really like a lot of the features of the script and I would prefer to keep it active, but it is getting annoying that videos and gifs take two clicks to start and then pause whenever I scroll.

**Comment by Phidica** [comment]
Oh, okay. Following a hunch after noticing #30 I tried just turning off the `hideMessagesDrawer` setting and now videos and gifs play uninterrupted again. I don't really mind keeping the messages drawer visible so this is a fine workaround for me. Hopefully it works for anyone else with this problem.
