### ISSUE TITLE
Suggestion: Switch project over to Typescript?

### ISSUE THREAD

**Issue by flleeppyy** [insin/tweak-new-twitter#37]
Seeing as there's lots of JSDoc comments for setting types, I would like to suggest that the project switches to Typescript.
I'm currently trying to poke around the project and VSCode just doesn't autofill things for me for variables and such

**Comment by insin** [comment]
Is it possible you have something in your global VS Code settings which stops it from using its built-in TypeScript language service for JavaScript?

I have it enabled via the `jsconfig.json` in the repo and all the regular TypeScript stuff works for me, which is why it's my preferred way to make use of TypeScript:

![Code_ZRreogtNbe](https://user-images.githubusercontent.com/226692/125571338-3e5b79a9-ddb2-4d07-aa0d-dde4b617221d.png)

I don't want to port it to TypeScript because I don't want a compile step, and the main script is also a valid user script, which lets me easily tweak it via Greasemonkey and test new changes there for a while before moving them over to the next extension version.

Not having a compile step also allows me to skip a step when submitting new versions of the Firefox add-on.
