### ISSUE TITLE
Non-verified accounts QRT'ing a verified account hides the QRT

### ISSUE THREAD

**Issue by flleeppyy** [insin/tweak-new-twitter#38]
When choosing to have Verified accounts set to Hide, it also hides tweets of those who are not verified, who are quote retweeting the tweet of someone who's verified.

**Comment by insin** [comment]
That's intended behaviour, but also completely accidental - this was a bit of a joke feature to simulate what your timeline would look like without verified users, and if there were no verified users there would be no tweets to quote 🐱

I have plans for future versions to be more intentional about what happens when people share content you're ignoring via this extension or via Twitter's built-in blocking and muting functionality - e.g. if you've blocked a user and someone QRTs them, you see the quoter's comment but the quoted tweet says "This tweet is not available" (or something like that, don't have an example to hand) instead of hiding the entire thing from your Timeline.
