### ISSUE TITLE
Who To Follow and other Twitter Suggestions are bleeding in.

### ISSUE THREAD

**Issue by TsukiZero** [insin/tweak-new-twitter#41]
Needs an update urgently.

And yes, tested both userscript and addon.

Managed to somewhat clean it up by adding the following rules to my uBlock Origin:

> twitter.com##[role="tablist"]
> twitter.com##[role="heading"][aria-level="2"]:has-text(Topics to follow):xpath(../../..)
> twitter.com##[href="/i/topics/picker/home"][role="link"]:xpath(../..)
> twitter.com##[aria-label="Timeline: Carousel"]:xpath(../../..)
> twitter.com##[d="M12.225 12.165c-1.356 0-2.872-.15-3.84-1.256-.814-.93-1.077-2.368-.805-4.392.38-2.826 2.116-4.513 4.646-4.513s4.267 1.687 4.646 4.513c.272 2.024.008 3.46-.806 4.392-.97 1.106-2.485 1.255-3.84 1.255zm5.849 9.85H6.376c-.663 0-1.25-.28-1.65-.786-.422-.534-.576-1.27-.41-1.968.834-3.53 4.086-5.997 7.908-5.997s7.074 2.466 7.91 5.997c.164.698.01 1.434-.412 1.967-.4.505-.985.785-1.648.785z"]:xpath(../../../../../..)
> twitter.com##[href^="/i/connect_people"][role="link"]:xpath(../..)
> twitter.com##[aria-level="2"][role="heading"]:has-text(Who to follow):xpath(../../..)

**Comment by ehrzuli** [comment]
Hello, this is happening to me, too. Yesterday (for me, anyway) Twitter on desktop started removing the "latest tweet" toggle from the top of the page and setting it automatically back to its algorithm, including all the liked tweets and other suggestions. Logging out and logging back in brings the toggle back, but only for a short period of time. I actually downloaded this extension in the hopes that it would correct it, and it did for a time, but it just happened to me again while I had the extension running.

I don't know anything about code like the above poster, but wanted to throw my two cents in as it looks like Twitter is trying to force changes on us again. Otherwise loving the extension!

**Comment by TsukiZero** [comment]
I've tweaked my filters a bit more, but I'm on the phone now so I can't
share it at this moment

**Comment by insin** [comment]
@ehrzuli: 

> I don't know anything about code like the above poster, but wanted to throw my two cents in as it looks like Twitter is trying to force changes on us again. Otherwise loving the extension!

If Twitter completely removes Latest Tweets, then this extension will be updated to filter out all the algorithmic crap from your timeline (that's what [the Old Twitter version of it](https://github.com/insin/manage-twitter-engagement#manage-twitter-engagement) used to do).

Filtering out irrelevant crap from the algorithmic timeline turns it into a worse version of Latest Tweets, so I don't want to do it unless my hand is forced by the removal of Latest Tweets.

The A/B test on removing it seems to have stopped for now, though.

**Comment by insin** [comment]
v1.28 fixed a bunch of bugs which could have caused this - if you see it happening again, please check if the script has stopped doing anything else on the page too and create an issue with what you were doing before it happened, that usually indicates the app was re-rendered and we didn't pick it up for some reason.
