### ISSUE TITLE
Suggestion: do something about replies loading bit by bit with "more tweets" at the bottom

### ISSUE THREAD

**Issue by grishka** [insin/tweak-new-twitter#72]
https://twitter.com/grishka11/status/1438608729281339408

This is apparently new and it drives me absolutely nuts. Would be really nice to have a way to undo this and make that page show replies, all of them at once like before, and nothing else.

**Comment by grishka** [comment]
I found out that adding `?s=20` to the URL reverts the frustration-free behavior of there being no "more tweets" section, all replies being visible and them getting loaded on scroll. So it should be easier than I initially thought.

**Comment by insin** [comment]
More Tweets seems to come and go, the hardest thing with trying to deal with it is being able to consistently get it to appear.

I don't want to add any auto-clicking of stuff in tweet timelines because of the potential of Twitter changes which break them or make the auto-clicking do something the user doesn't expxect
