### ISSUE TITLE
j/k navigation borked

### ISSUE THREAD

**Issue by yetzt** [insin/tweak-new-twitter#85]
navigating between tweets with keyboard appears to be broken with this addon, it would be delightful if this could be fixed.

**Comment by insin** [comment]
Unfortunately I don't think there's anything we can do about this - Tweak New Twitter works by changing the style of timeline tweets which should be hidden every time the timeline is updated, which the underlying React app doesn't know about, so when you hit j/k it's going to go to the next tweet in the timeline regardless of whether it's currently visible on your screen.

I don't think there's anything we can do to access or modify the internal state the app uses for this.

**Comment by yetzt** [comment]
thats frustrating. thank you for investigating, it's very appreciated.

**Comment by flamingspinach** [comment]
I don't know anything about React, but just spitballing here -- would it be possible to e.g. add a listener that detects when an invisible tweet is selected and automatically moves to the next visible tweet? (You'd need to also externally track what direction the user was moving to determine whether "next" means upwards or downwards, though.)

If it's too difficult and/or fragile to meddle in the internals of the React app, you might be able to accomplish it by just repeating the sent j/k keystroke the appropriate number of times, so that the app is treated as a black box. (?)
